services:
  - type: web
    name: instasave-downloader
    runtime: python
    envVars:
      - key: PORT
        value: 10000
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    disk:
      name: video-storage
      mountPath: /var/lib/videos
    envVars:
      - key: WEB_CONCURRENCY
        value: 1
      - key: PYTHONUNBUFFERED
        value: 1
    healthCheckPath: /health